# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "Lyle0411"
repo_name: "clp-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: True

# file paths
json_readme_path: './docs/clp-daily.json'
json_gitpage_path: './docs/clp-daily-web.json'
json_wechat_path: './docs/clp-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "CR":
        filters: ["Code Review Automate", "Code Review"]
    "TDM":
        filters: ["Technical Debt Management Automate", "Technical Debt Management"]
    "CS":
        filters: ["Code Smell Automate", "Code Smell"]
    "SCA":
        filters: ["Static Code Analysis Automate", "Static Code Analysis"]
    "DCA":
        filters: ["Dynamic Code Analysis Automate", "Dynamic Code Analysis" ]
    "CCC":
        filters: ["Code Compliance Checking Automate","Code Compliance Checking"]


